version: 2

sources:
  - name: raw
    description: Dados brutos carregados do banco transacional AdventureWorks.
    database: analytics
    schema: raw
    config:
      loaded_at_field: _loaded_at
      freshness:
        warn_after:
          count: 25
          period: hour
        error_after:
          count: 48
          period: hour

    tables:
      - name: salesorderheader
        description: Cabeçalho dos pedidos de venda.
        config:
          loaded_at_field: modifieddate
          meta:
            freshness_type: business

      - name: salesorderdetail
        description: Itens dos pedidos de venda.
        config:
          loaded_at_field: modifieddate
          meta:
            freshness_type: business

      - name: customer
        description: Cadastro de clientes.

      - name: salesterritory
        description: Territórios comerciais.

      - name: product
        description: Cadastro de produtos.

      - name: person
        description: Cadastro de pessoas.

      - name: store
        description: Cadastro de lojas associadas aos clientes empresariais.

      - name: specialoffer
        description: Cadastro das ofertas especiais aplicadas aos produtos vendidos.

      - name: salesperson
        description: Cadastro e informações comerciais dos vendedores.

      - name: employee
        description: Cadastro profissional dos funcionários da empresa.
